### ISSUE TITLE
Make lines with icons thinner

### ISSUE THREAD

**Issue by AsValeO** [olegtarasov/VSIconizer#1]
Nice tool, Oleg! 
Make lines with icons thinner, like default ones with text. Or better even more thinner.
The goal is to save place, lets save it all the way.
Уточню по-русски для лучшего понимания =):
Я имею ввиду, что сами синие полоски получаются шире/выше чем обычные с текстом.
У меня они слева, справа и снизу. Таким образом много места отнимается у рабочей зоны, гораздо больше чем с обычным текстом. Думаю, их нужно сделать даже меньше стандартных. Спасибо.

**Comment by olegtarasov** [comment]
Hi @AsValeO! My goal in making this extension was not actually to save space, but to make tabs easier to find visually. I experimented with small tab sizes at first, and found it was harder to locate and activate tabs. So I made tab margins larger than the original size. I know it doesn't suit everyone's taste, and maybe this can be solved by adding a settings page for the extension. Unfortunately, I don't have the time to do it right now, but if you or somebody else feels up to it, I would appreciate a pull request :)

Я специально сделал поля больше, т. к. цель была не в экономии места, а в том, чтобы быстрее выцеплять табы глазами и попадать в них мышкой. Можно было бы добавить раздел в найстройки VS для экстеншона, и задавать там толщину полей, но на это сейчас совершенно нет времени :(

**Comment by olegtarasov** [comment]
@AsValeO 
Added an option page in `VS Options → Environment → Iconizer` to be able to change icon margins.
5c85fdd0e4f1a805b7dcd3fa886b72794565766e
